In [12]:
import os
import re
dir = r"C:\Users\kekuak\Documents\manual_score_transcriptions\transcripts\output_mono\output_mono"
for file in os.listdir(dir):
    if file.endswith('.sbv') and file.startswith('r'):
        print(file)

r_IRCall_100161465830210103.sbv
r_IRCall_200101475040210108.sbv
r_IRCall_200102400560210301.sbv
r_IRCall_200103777260210302.sbv
r_IRCall_200106248240210109.sbv
r_IRCall_200106256840210109.sbv
r_IRCall_200106814470210302.sbv
r_IRCall_200106823050210414.sbv
r_IRCall_200107342640210110.sbv
r_IRCall_200107348470210302.sbv
r_IRCall_200108935370210302.sbv
r_IRCall_200111916650210415.sbv
r_IRCall_200111930270210302.sbv
r_IRCall_200113015540210111.sbv
r_IRCall_200114164870210303.sbv
r_IRCall_200114396670210303.sbv
r_IRCall_200114421370210303.sbv
r_IRCall_200115113870210303.sbv
r_IRCall_200116545340210111.sbv
r_IRCall_200121668840210112.sbv
r_IRCall_200122097270210304.sbv
r_IRCall_200122100140210112.sbv
r_IRCall_200123810470210304.sbv
r_IRCall_200124230640210113.sbv
r_IRCall_200124256740210113.sbv
r_IRCall_200124706270210304.sbv
r_IRCall_200125903870210304.sbv
r_IRCall_200125971150210417.sbv
r_IRCall_200126209570210304.sbv
r_IRCall_200126498670210304.sbv
r_IRCall_200126641350210417.sbv
r_IRCall

In [3]:
'j' in 'akshay'

False

In [6]:
set(['a', 'b', 'c']) - set(['a'])

{'b', 'c'}

In [11]:
'akshay'[0]

'a'

In [16]:
import pandas as pd
pd.__version__

'1.2.5'

In [4]:
import nltk
from nltk.tokenize import word_tokenize

In [6]:
word_tokenize('')

[]

In [1]:
import torch

In [9]:
a = torch.tensor([[[[1,2]], [[3,4]]], [[[5,6]], [[7,8]]]])
a.shape

torch.Size([2, 2, 1, 2])

In [19]:
b = a.view(-1, *a.size()[2:])

In [18]:
torch.cat([t for t in a], dim=0)

tensor([[[1, 2]],

        [[3, 4]],

        [[5, 6]],

        [[7, 8]]])

In [23]:
b.reshape(*a.size()[0:2], -1)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [24]:
c = torch.tensor([[1,2], [3,4], [4,5], [6,7]])

In [27]:
c.reshape(2,2,-1)

tensor([[[1, 2],
         [3, 4]],

        [[4, 5],
         [6, 7]]])